[package]
name = "deduplication_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = "0.5"
calamine = "0.18"
csv = "1.1"
rayon = "1.7"
log = "0.4"
env_logger = "0.10"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
